# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app


# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m spacy download en_core_web_lg

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Expose the port your app runs on
EXPOSE 5001

# Define the command to run your application
CMD ["python", "app.py"]
